src/lib/meson.build

Very small change in Meson config to allow zck to build
with a static library instead of just a dynamic one.
To use, run "meson --default-library=static build"
The resulting binaries should now be statically linked
with zck (resuilting in fewer dependencies).

Enable build with static library for zck

---

src/lib/dl/multipart.c

Reference: https://tools.ietf.org/html/rfc2046#section-5.1.1
According to RFC 2046, the boundary parameter in the Content-Type
header can optionally be quoted with double quotes.
Fix zchunk's boundary parsing so that double quotes are stripped when
found.
This is causing dnf to fail behind proxies, when using zchunk.
https://bugzilla.redhat.com/show_bug.cgi?id=1706627

Multipart boundary field can be quoted.

---

src/unzck.c
src/zck.c
src/zck_dl.c
src/zck_gen_zdict.c
test/copy_chunks.c

When creating files, zchunk did not obey the users's umask(2) setting.

Open files with permissions 0666 and let umask(2) do its job.

---

doc/unzck.1
doc/zck.1
doc/zck_delta_size.1
doc/zck_gen_zdict.1
doc/zck_read_header.1
doc/zckdl.1
meson.build

Hi,
What do you think about these manual page stubs? I know that they are very brief and that they currently do not really contain much more information than the usage messages themselves. However, in some cases (and with some old-fashioned people such as myself or the ones setting the Debian project policies :)) even a brief manual page is preferable to none.
If there should be any concern as to keeping the manual pages up-to-date with the changing source, I could tentatively make a commitment to taking care of this in the future. I might also be persuaded to fill out these stubs a bit :)
Thanks in advance, and keep up the great work!
G'luck,
Peter

Add manual page stubs for the command-line utilities.

---

meson.build
src/lib/index/index_read.c

As mentioned in #24 there are the 2 problems with compiling on macOS which this PR resolves:
1. <endian.h> is <machine/endian.h> on MacOS
2. argp-standalone should be searched for on MacOS
Tests pass on macOS 10.15.
In this specific snippet, my libraries are installed in non-standard locations.
```
oooo@oooos-MacBook-Pro zchunk4 % export C_INCLUDE_PATH=/nix/store/zgkjdw988darkzkyy198zfc71d4ck1n0-argp-standalone-1.3/include:/nix/store/rk45fz45anwv8xmhzkzdbgbila92lrh1-zstd-1.4.5-dev/include
oooo@oooos-MacBook-Pro zchunk4 % export PKG_CONFIG_PATH=/nix/store/m95ip2v1f5y339a5clma03ia6lxhg4nf-curl-7.74.0-dev/lib/pkgconfig:/nix/store/rk45fz45anwv8xmhzkzdbgbila92lrh1-zstd-1.4.5-dev/lib/pkgconfig:/nix/store/r7glhc06wpn3bvsyd7aaw0b1nlf5im7n-openssl-1.1.1i-dev/lib/pkgconfig
oooo@oooos-MacBook-Pro …
```

macOS: Use correct endian.h & use argp-standalone

---

src/lib/zck.c

It was allocated `ascii_checksum_to_bin` but never freed.

Fix memory leak of zck->prep_digest

---

meson.build

Without this the detection will fail on some systems (in this case openSUSE Tumbleweed / GCC10) because of Werror and the missing return inside a non void function.

meson: Fix argp detection, prevent Werror=return-type

---

src/zck_gen_zdict.c

Fix build on cygwin ( #42 )
```
$ ninja test
[0/1] /usr/bin/meson test --no-rebuild --print-errorlogs
1/30 create and validate empty zchunk file                               OK              0.16s
2/30 check version info in zck                                           OK              0.67s
3/30 check version info in unzck                                         OK              1.23s
4/30 check version info in zckdl                                         OK              1.51s
5/30 check version info in zck_read_header                               OK              1.04s
6/30 check version info in zck_delta_size                                OK              1.60s
7/30 check opening file with optional flags                              OK              1.47s
8/30 checksum with non-hex …
```

Fix build on cygwin

---

zchunk_format.txt

This flag indicates that the zchunk file will contain uncompressed chunk checksums as well as the normal compressed chunk checksums so a zchunk file can be downloaded against an uncompressed source, though it will probably need to be decompressed on the fly to make an uncompressed target.

Add uncompressed source flag to zchunk_format.txt

---

include/zck.h.in
src/lib/buzhash/buzhash.c
src/lib/buzhash/buzhash.h
src/lib/comp/comp.c
src/lib/comp/nocomp/nocomp.c
src/lib/comp/zstd/zstd.c
src/lib/dl/dl.c
src/lib/dl/multipart.c
src/lib/dl/range.c
src/lib/error.c
src/lib/hash/hash.c
src/lib/header.c
src/lib/index/index_common.c
src/lib/index/index_create.c
src/lib/index/index_read.c
src/lib/io.c
src/lib/zck.c
src/lib/zck_private.h
src/zck.c
src/zck_read_header.c
zchunk_format.txt

Hi Jonathan,
please consider this as RFC and after just testing that the uncompressed checksum is part of the index and it is reported back by zck_read_header, and after running zck / unzck on quite big files.
This set implements the new format as specified in the uncompressed_source branch. The checksum for uncompressed data is stored then in the index and the hash is computed together with the one for the compressed chunk.
In the series there are also:
Drop warning when OLD_ZSTD is set
----------------------------------------------------- 
It is a nitpick, this just drop a warning when OLD_ZSTD is set
Drop assert in zmalloc and raise runtime error 
--------------------------------------------------------------
This is an issue using the library on embedded system. An allocation on the …

Introduce checksum for uncompressed data in the header

---

include/zck.h.in
src/lib/comp/comp.c
src/lib/hash/hash.c
src/lib/header.c
src/lib/index/index_create.c
src/lib/index/index_read.c
src/lib/zck.c
src/lib/zck_private.h
src/zck.c

This PR has a number of cleanup commits, but the main thing it adds is a `--compressed-format=(zstd|none) argument` to `zck`

Allow specification of `--compressed-format` in `zck`

---

include/zck.h.in

function declarations should always explicitly say no argument is expected,
as in C 'foo bar()' means bar can take any parameter.
This was noticed when building another project with -Wall -Wextra and getting
the following warning on installed header:
```
/usr/include/zck.h:66:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
66 |     __attribute__ ((warn_unused_result));
|     ^~~~~~~~~~~~~
/usr/include/zck.h:325:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
325 |     __attribute__ ((warn_unused_result));
|     ^~~~~~~~~~~~~
```

fix -Wstrict-prototypes warning

---

.github/environment.yml
.github/workflows/main.yml

Hi @jdieter this adds a github action to test Linux & macOS builds (successfully).
You can find a run here: https://github.com/wolfv/zchunk/actions/runs/1612528834
This runs on free machines provided by GitHub. 
Once you merge this, I would rebase my PR for Windows and start testing that, too.
Note that in this case I use `mamba` & `conda-forge` to obtain the dependencies. It's convenient because we have the same source of dependencies for Linux, macOS and Windows.
We can later also integrate an alternative action that runs against Fedora 35 in a docker container or similar.

add github action

---

meson.build

Note that this also bumps the minimum meson version to 0.53.0

Verify that include directory exists before trying to include it

---

.github/lint_environment.yml
.github/workflows/linter.yml
.pre-commit-config.yaml

This adds a `.pre-commit-config.yml` config and a github actions based linter step. 
Currently it only checks for end of file newlines (and auto-corrects them when running locally with `pre-commit run --all`.
There are a couple other nice linter steps supported with `pre-commit`. A list of pre-provided hooks is here: https://github.com/pre-commit/pre-commit-hooks
One I find personally quite useful is `clang-format`. 
That could be configured like so:
```
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
rev: master
hooks:
-   id: clang-format
args: [--style=file]
```
And would require an `.clang-format` in the root of the repo (e.g. https://github.com/mamba-org/mamba/blob/master/.clang-format). We'd need to figure out the proper values to match the current style of zchunk.

pre-commit config & github linter CI

---

src/lib/zck.c

I noticed that the debug log message was overrunning because we only allocate `length` bytes and no `\0` terminator.

print only length characters

---

test/meson.build

Hi,
What do you think about the attached trivial patch that handles a test file checksum change in the interim 1.4.10 version of libzstd? (It has been tagged with a lot of bugfixes and improvements, but it is not listed on the releases page)
Thanks in advance, and keep up the great work!
G'luck,
Peter

Let the tests also pass with libzstd-1.4.10.

---

.gitattributes

Hi,
What do you think about this trivial change that stops Git from modifying the (binary) *.zck test files at all? At least for me, with Git 2.35.1 on a Debian testing system, the attributes file was not enough to stop Git from converting CR/LF to LF in the compressed files, thus breaking things in various ways.
Thanks in advance, and keep up the great work!
G'luck,
Peter

Turn off EOL handling for the *.zck test files.

---

.github/workflows/main.yml
meson.build
subprojects/argp-standalone.wrap

Currently using my own fork of [`argp-standalone`](https://github.com/argp-standalone/argp-standalone) with a few fixes I submitted upstream [here](https://github.com/argp-standalone/argp-standalone/pull/7) but should fix the wrap build on windows.

meson: fix argp-standalone wrap and find_library

---

subprojects/argp-standalone.wrap

Now that `1.5.0` is tagged we can use that instead of a commit hash.

argp-standalone.wrap: update to version 1.5.0

---

.pre-commit-config.yaml
README.md

zstd now offers rsync-friendly output, so mentioning that zchunk files are efficient over rsync misses the primary benefit zchunk has, namely that zchunk files can be downloaded efficiently from normal web servers that support range requests (which is basically all of them, except for some rather strange proxies).
Fixes #86 
Signed-off-by: Jonathan Dieter <jdieter@gmail.com>

Clarify what the primary benefit of zchunk is

---

include/zck.h.in
src/lib/comp/comp.c
src/lib/header.c
src/lib/io.c
src/lib/zck.c
src/lib/zck_private.h

There are situations where we need to recreate the zchunk header for an uncompressed file without actually writing out the zchunk file.  This commit allows setting an `ioption`, `ZCK_NO_WRITE`, that will go through the full process of creating the zchunk file without actually writing it to disk, leaving you with a complete zchunk header in the end.

Add ZCK_NO_WRITE option to disable writing to a file

---

meson.build

The test fails with clang erroneously
Upstream-Status: Pending

Dont let clang optimize away a meson check

---

src/zck_delta_size.c

Help the user by not having to calculate relative savings or the number of nonmatching chunks.

Provide more statistics

---

src/lib/header.c

Free digests to fix memory leak in `read_lead`.
It also adds a space in the `Expected: %s Actual: %s` format string which I believe was missing.

Free digests to fix mem leak in read_lead
